# Development Docker Compose with Hot Reload
version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=trading_user
      - POSTGRES_PASSWORD=trading_password
      - POSTGRES_DB=trading_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trading_user -d trading_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: open-paper-trading-mcp_app:latest
    restart: unless-stopped
    volumes:
      # Mount source code for hot reload
      - .:/app
      - robinhood_tokens:/app/.tokens
      - trading_logs:/app/.logs
      # Exclude certain directories to avoid conflicts
      - /app/__pycache__
      - /app/.pytest_cache
    ports:
      - "2080:2080"
      - "2081:2081"
    environment:
      - DATABASE_URL=postgresql+asyncpg://trading_user:trading_password@db:5432/trading_db
      - ENVIRONMENT=development
      - DEBUG=True
      - ROBINHOOD_TOKEN_PATH=/app/.tokens
      # Enable hot reload for Python
      - PYTHONUNBUFFERED=1
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    volumes:
      # Mount source code for hot reload
      - ./frontend:/app
      # Exclude node_modules to avoid conflicts
      - /app/node_modules
    ports:
      - "3000:5173"  # Map to Vite dev server port
    environment:
      # Enable hot reload
      - CHOKIDAR_USEPOLLING=true
      - FAST_REFRESH=true
    depends_on:
      - app

volumes:
  postgres_data:
  robinhood_tokens:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/tokens
  trading_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/logs