version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=trading_user
      - POSTGRES_PASSWORD=trading_password
      - POSTGRES_DB=trading_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trading_user -d trading_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "2080:2080"
      - "2081:2081"
    environment:
      - DATABASE_URL=postgresql+asyncpg://trading_user:trading_password@db:5432/trading_db
      - ENVIRONMENT=development
      - DEBUG=True
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
