version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=trading_user
      - POSTGRES_PASSWORD=trading_password
      - POSTGRES_DB=trading_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trading_user -d trading_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: open-paper-trading-mcp_app:latest
    restart: unless-stopped
    volumes:
      - .:/app
      - robinhood_tokens:/app/.tokens
      - trading_logs:/app/.logs
    ports:
      - "2080:2080"
      - "2081:2081"
    environment:
      - DATABASE_URL=postgresql+asyncpg://trading_user:trading_password@db:5432/trading_db
      - ENVIRONMENT=development
      - DEBUG=True
      - ROBINHOOD_TOKEN_PATH=/app/.tokens
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: open-paper-trading-mcp_frontend:latest
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - app

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - MCP_HTTP_URL=http://app:2081/mcp
    depends_on:
      app:
        condition: service_started
    volumes:
      - ./tests/evals:/app/tests/evals
      - ./examples/google_adk_agent:/app/examples/google_adk_agent

volumes:
  postgres_data:
  robinhood_tokens:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/tokens
  trading_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/logs
