[project]
name = "open-paper-trading-mcp"
version = "0.1.0"
description = "Open Paper Trading MCP - A dual-interface paper trading simulation platform"
readme = "README.md"
requires-python = ">=3.11"
license = "Apache-2.0"
authors = [
    { name = "Wes Etheredge", email = "jwesleye@gmail.com" }
]

# Minimal dependencies for MCP server functionality
dependencies = [
    # Core FastAPI and server dependencies
    "fastapi",
    "uvicorn[standard]",
    "pydantic[email]",
    "pydantic-settings",
    # Essential utilities
    "python-dotenv",
    "httpx",
    "aiohttp",
    # Database (minimal)
    "sqlalchemy",
    "asyncpg",
    "aiosqlite",
    "alembic",
    # Authentication
    "python-jose[cryptography]",
    "passlib[bcrypt]",
    # Trading specific (keep minimal)
    "robin-stocks",
    "numpy",
    "scipy",
    "pytz",
    # System utilities
    "psutil",
    "toml",
    # Google API for ADK
    "google-api-python-client",
    "mcp==1.12.2",
    "fastmcp==2.7.0",
    "psycopg2-binary>=2.9.10",
    "email-validator>=2.2.0",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-asyncio",
    "pytest-cov",
    "pytest-mock",
    "mypy",
    "ruff",  # Replaces black, isort, flake8
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["app*"]
exclude = ["tests*", "reference_code*", "examples*"]

[tool.mypy]
python_version = "3.11"
exclude = [
    "reference_code/",
    "examples/",
]
ignore_missing_imports = true
warn_return_any = false
warn_unused_ignores = false

[tool.ruff]
line-length = 88
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "I", "N", "UP", "B", "A", "C4", "SIM", "RUF"]
ignore = ["E501"]

[dependency-groups]
dev = [
    "types-toml>=0.10.8.20240310",
]
